### ISSUE TITLE
how to get memory usage reported?

### ISSUE THREAD

**Issue by vjcitn** [mllg/batchtools#117]
I am just transitioning to batchtools ... the getJobTable for my
initial forays reports NA under memory.  Do I need to set a parameter
to get the memory consumption estimates recorded?

**Comment by mllg** [comment]
Sorry for the late response. 

Indeed, you need to set the resource `measure.memory` to enable a heuristic based on `gc()` (<https://mllg.github.io/batchtools/reference/submitJobs.html#note>). It turned out that repeatedly calling `gc()` is quite expensive if you have many thousands of chunked jobs. Therefore this is disabled per default. You can enable it for all future registries by setting 
```r
default.resources = list(measure.memory = TRUE)
```
in your config. I will try to support <https://github.com/sosy-lab/benchexec> in the future which gives more reliable measurements (i.e. allocations in compiled or threaded code).

**Comment by vjcitn** [comment]
Just wondering whether the comment on benchexec connection for batchtools has been followed up.  Thanks.

**Comment by mllg** [comment]
Unfortunately, no, not yet.
