### ISSUE TITLE
Test failure with dev version of tibble

### ISSUE THREAD

**Issue by krlmlr** [mllg/batchtools#150]
Tests seem to rely on output, which has changed slightly because we're now using pillar to format the columns: https://github.com/tidyverse/tibble/blob/e5ae87aaaf6a2643d66073193196f5061041bdfd/revdep/problems.md#batchtools

Relying on output produced by other packages feels brittle. Can you please adapt the test to avoid checking the exact formatting of a tibble output?

**Comment by mllg** [comment]
As far as I can tell this has nothing to do with `tibble`. I'm calling a function which generates output to stdout/stderr and  testthat just swallows it (see https://github.com/r-lib/testthat/issues/460). 

This should already have been fixed in batchtools devel (c.f. https://github.com/mllg/batchtools/blob/master/tests/testthat/test_grepLogs.R#L5).

**Comment by krlmlr** [comment]
Thanks, this should be sufficient for us to release tibble.
