### ISSUE TITLE
findConfFile missing from pkgdown reference

### ISSUE THREAD

**Issue by maelle** [mllg/batchtools#256]
Maybe you could use regex or another method to group functions in your reference without having to remember to add them? (Or maybe you don't want findConfFile in the ref)

**Comment by maelle** [comment]
What I mean reg using regex. https://pkgdown.r-lib.org/articles/pkgdown.html#reference

Another method is
* to use the `@family`  tag in R files cf e.g. https://github.com/ropensci/stplanr/blob/bf5543180e3ef724b57f2b622e75d0a4022cf53f/R/linefuns.R#L11

* to use `has_concept` in the pkgdown reference config cf e.g. https://github.com/ropensci/stplanr/blob/bf5543180e3ef724b57f2b622e75d0a4022cf53f/_pkgdown.yml#L14 website https://docs.ropensci.org/stplanr/reference/index.html
the advantage of this approach (that I've only used once though, this package above isn't mine) is that you get the grouping in the pkgdown reference but locally in the man pages you get the "See also" stuff. https://docs.ropensci.org/stplanr/reference/is_linepoint.html#see-also Now, this is more work, and I'm not sure how much usage the "See also" sections get.

**Comment by maelle** [comment]
From `?findConfFile` I'd like to find `setSystemConf` :-) (I'm working on a blog post about packages using config dirs and such)

**Comment by maelle** [comment]
Is it so that the user has to create the configuration file by hand? (I'm working on a blog post about package configs, not really using batchtools).

**Comment by mllg** [comment]
`findConfFile()` is an internal function (and has keyword `internal`), I don't want it listed in the package index. IIRC it was exported so that third party packages (`future.batchtools`?) can call it, but not intended to be called by a user.

You have to create configuration files by hand to select a parallelization backend. See argument `conf.file` in https://mllg.github.io/batchtools/reference/makeRegistry.html for possible locations. Let me know if you have more questions.

**Comment by maelle** [comment]
Aaah ok thanks, it makes sense!
