### ISSUE TITLE
job.name and arrayjobs equivalents in batchtools SGE template

### ISSUE THREAD

**Issue by thercast** [mllg/batchtools#29]
I've begun experimenting with `batchtools` by migrating some previous projects that used `BatchJobs` and `BatchExperiments`.  We use SGE on our cluster.  Here are the contents of my working template file (much of which was copied from my existing template with `BatchJobs`):

```
#!/bin/bash

# The name of the job, can be anything, simply used when displaying the list of running jobs
#$ -N "my_job"
# Combining output/error messages into one file
#$ -j y
# Giving the name of the output log file
#$ -o <%= log.file %>
# One needs to tell the queue system to use the current directory as the working directory
# Or else the script may fail as it will execute in your top level home directory /home/username
#$ -cwd
# use environment variables
#$ -V
# define multiple cores per node
$ -pe smp <%= resources$n.cores %>
# use resource reservation
$ -R y

# we merge R output with stdout from SGE, which gets then logged via -o option
module load cluster-setup
module unload R
module load R/3.2.0
Rscript -e 'batchtools::doJobCollection("<%= uri %>")' /dev/stdout
exit 0
```

Everything works so that's great!  In my previous template I had the following that utilized `job.name` and `arrayjobs`:

```
# The name of the job, can be anything, simply used when displaying the list of running jobs
#$ -N <%= job.name %>

# use job arrays
#$ -t 1-<%= arrayjobs %>
```

You can see that I simply hard-coded a job name in my new template, but is there a more elegant way to define the job name dynamically?  Also how would I go about specifying arrayjobs?   Thanks for your great work on this package!

**Comment by mllg** [comment]
> Everything works so that's great! In my previous template I had the following that utilized job.name and arrayjobs:

Good to hear. Array jobs are now  supported rudimentarily (344297c8d11bcdad005de38d11206dd79ba50f85).
But note that (a) I cannot test this because I do not have a system supporting array jobs and (b) the interface might change. I have to find out how the schedulers process the output of array jobs.

For now, you can try two things: Set the resource `chunks.as.arrayjobs` to `TRUE`, submit the jobs chunked and teach your template file to handle the arrays:
```
#$ -t 1-<%= nrow(defs) %>
```

Regarding the job names: I  use the job hash, but this is completely up to you (you can use every variable stored in a JobCollection):
```
#$ -N bt_<%= job.hash %>
```

**Comment by thercast** [comment]
I've updated my template with your recommendation and everything works as expected.  Thanks @mllg !
