### ISSUE TITLE
does clusterFunctionsTorque use input template for anything?

### ISSUE THREAD

**Issue by sorhawell** [mllg/batchtools#46]
I inspect [makeClusterFunctionsTorque.R](https://github.com/mllg/batchtools/blob/master/R/clusterFunctionsTorque.R) and I cannot understand how you handle the template, it seems you read the template file once ` template = cfReadBrewTemplate(template, "##") `, and then drop it as it is not returned by the function. How is the template then added to the registry via a conf.file? How is the template used when submitting jobs? Does the current version of batchtools rather rely on that `batchtools:::findTemplateFile` always recover some template file later?

all the best

**Comment by mllg** [comment]
> I inspect makeClusterFunctionsTorque.R and I cannot understand how you handle the template, it seems you read the template file once template = cfReadBrewTemplate(template, "##"), and then drop it as it is not returned by the function.

You are right, I read the template file once. But the variable will not be garbage collected, because it lives in the environment of the returned functions. Here is a small example to demonstrate this mechanism (called [closure](https://en.wikipedia.org/wiki/Closure_(computer_programming))):
```r
pow = function(p) {
  force(p)
  function(x) x^p
}
square = pow(2)
square(1:10)
root = pow(0.5)
root(1:10)

ls.str(environment(square))
```

After parsing the template once during construction with `makeClusterFunctionsTorque`, the template is stored as string in the environment of the functions:
```r
ee = environment(reg$cluster.functions$submitJob)
ls.str(ee)
ee$template
```
If passed to `cfBrewTemplate` the variable `template` will get automatically resolved to variable previously defined in respective scope/environment.


Regarding the hooks: 
Sorry, I was pointing you in the wrong direction in the other issue. To set the hooks, put something like this in your config file:
```r
# vanilla cluster functions implementations without hooks
cluster.functions = makeClusterFunctionsTorque(template = "~/torque.tmpl")

# hooks is initialized as an empty list, thus we can just set one here
cluster.functions$hooks$pre.submit = function(...) Sys.sleep(2)
```

**Comment by sorhawell** [comment]
I salute you !
I have overlooked the closure part until now.
thx
