### ISSUE TITLE
Problem with job.id and qsub on SGE

### ISSUE THREAD

**Issue by markb729** [mllg/batchtools#67]
I have been migrating to batchtools from batchjobs on a SGE system but I am running into a problem when submitting jobs with qsub:

Submitting 10 jobs in 10 chunks using cluster functions 'SGE' ...
Error in submitJobs() : 
  Fatal error occurred: 101. Command 'qsub' produced exit code 1. Output: 'Unable to run job: denied: "950405d6cc6c655225ffe092a43a970d" is not a valid object name (cannot start with a digit)
Exiting.'

As a workaround, I used chunkIds() to create an id data.frame, prepending "Job" to the numerical job.id:

 job.id chunk
 1:   Job1     1
 2:   Job2     1
 3:   Job3     1
 4:   Job4     1
 5:   Job5     1
 6:   Job6     1
 7:   Job7     1
 8:   Job8     1
 9:   Job9     1
10:  Job10     1

But when I use addJobTags(ids=ids,reg=reg), I receive the error:

Error in addJobTags(ids = ids, reg = reg) : 
  Assertion on 'column 'job.id'' failed. Must be of class 'integerish', not 'character'.

By intergerish, I think mixed alphanumeric. But must the job.id **begin** with an integer? Or, more simply, am I using the wrong procedure to define job.ids? This was probably not the intended use of add JobTags...

Thanks,
Mark

**Comment by mllg** [comment]
> Submitting 10 jobs in 10 chunks using cluster functions 'SGE' ...
> Error in submitJobs() :
> Fatal error occurred: 101. Command 'qsub' produced exit code 1. Output: 'Unable to run job: denied: "950405d6cc6c655225ffe092a43a970d" is not a valid object name (cannot start with a digit)
> Exiting.'

This has been already fixed in https://github.com/mllg/batchtools/commit/9dc0d55a06a78493829a06c70f62746837c8c8e7 for batchtools-0.9.1.


> As a workaround, I used chunkIds() to create an id data.frame, prepending "Job" to the numerical job.id

There are several different ids in batchtools:

1. The job ids which are exposed to the user as integer values.
2. The batch id, which is a string assigned by the batch system during submission
3. The job collection hash, which is a unique identifier for a group of jobs submitted chunked to the batch system.

All of them are stored in `reg$status`. 

SGE had a problem with the job collection hash (3) starting with a number, because this hash is also used as the name of the job on the batch system (via option `-N`). I think you mixed this up with (1) so the error message looks correct to me.

If you update to the devel version you should be fine.

**Comment by markb729** [comment]
Excellent! Thank you for the fix and further clarification.
