### ISSUE TITLE
possibility to use old registry with modified code

### ISSUE THREAD

**Issue by smilesun** [mllg/batchtools#96]
@berndbischl , @mllg 
Scenario 1:  I have run 20,000 jobs, and 1500 of them failed, and I found out that this is due to I made a mistake in the corresponding algorithm, after fixing the bug, I want to rerun this 1000 jobs again, but of course I don't want to rerun the 19,000 that is finished. One way to do this is of course to create another registry and submit 1000 jobs separately and then join the result table  with the 19,000. This is not so convenient, is there a way to do so like addAlgorithm(..., overwrite = TRUE) so it updates the RData file on disk and you could resubmit the failed jobs using the existed registry.
Scenario 2: Beyond that, you implemented new algorithms and also extend the configuration (The cartesian product  changed now), is there a way to keep track of the finished experiment and only submit jobs that are either with new configuration or with edited code?

**Comment by mllg** [comment]
1: Just add again, the algorithm gets overwritten

2: just add jobs, already defined jobs are automatically skipped and remain untouched. `addExperiments()` returns the ids of added jobs, so you directly get them here. Otherwise you can always call `findNotSubitted()` which is often sufficient. 

If you need more control, you can also tag jobs, see <https://mllg.github.io/batchtools/reference/Tags.html>.

**Comment by mllg** [comment]
Have you solved it?

**Comment by smilesun** [comment]
have not tried yet

**Comment by berndbischl** [comment]
@mllg assuming you have tests for the described functionality the question seems answered?

**Comment by mllg** [comment]
Sure.
